services:
  - type: web
    name: caresphere-backend
    env: docker
    plan: free
    dockerContext: ehs-backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: caresphere-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: caresphere-db
    plan: free
    databaseName: ehs
    user: ehs_admin
